apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain
  namespace: orftsmparis
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rain
  template:
    metadata:
      labels:
        app: rain
        version: v1
    spec:
      containers:
      - name: rain
        image: gcr.io/boreal-rain-256712/http-echo:latest
        env:
        - name: TEXT
          value: ' Rain Paris -> '
        - name: NEXT
          value: "yes-1.demo.acme.com:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rain
  namespace: orftsmparis
  labels:
    app: rain
spec:
  selector:
    app: rain
  ports:
  - name: http
    port: 8080
    targetPort: 8080
